# TODO Add a Dockerfile for just running the containerized application, not VSCode

ARG VARIANT=3-bullseye
FROM python:3.10

ARG OPENAI_API_KEY
ARG OPENAI_ORG_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_ORG_KEY=$OPENAI_ORG_KEY

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
# Remove imagemagick due to https://security-tracker.debian.org/tracker/CVE-2019-10131
&& apt-get purge -y imagemagick imagemagick-6-common

# Upgrade python packages due to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897
RUN python3 -m pip install --upgrade setuptools

# Install Chromium for web browsing
RUN apt-get install -y chromium-driver

# Install vim for command-line file editing
RUN apt-get install -y vim

# Install java and graphviz for PlantUML
RUN apt-get install -y default-jre graphviz

# Get PlantUML .jar
RUN wget -O plantuml.jar http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
RUN mkdir /usr/local/plantuml
RUN mv plantuml.jar /usr/local/plantuml/plantuml.jar

# Add pip requirements to image
COPY ../requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
   && rm -rf /tmp/pip-tmp
